<a href="https://colab.research.google.com/github/pablohf7/Curso_Analisis_Datos_Python/blob/main/tipos_y_estructura_de_datos_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lista = [0,1,2,3,4]
my_array = np.array(lista)
my_array

array([0, 1, 2, 3, 4])

In [ ]:
lista1=[1,2,3]
lista2=[10,20,30]
lista3=[100,200,300]

my_array1 = np.array(lista1)
my_array2 = np.array(lista2)
my_array3 = np.array(lista3)

In [ ]:
lista1+lista2+lista3

[1, 2, 3, 10, 20, 30, 100, 200, 300]

In [ ]:
my_array1+my_array2+my_array3


array([111, 222, 333])

In [ ]:
my_array1*my_array2

array([10, 40, 90])

In [ ]:
#ESTADISTICAS CON NUMPY
valores = np.array([1,3,4,5,1,5,7,3,5,2,8,9,2,2,3,5,1,7,3,6,1,1])
print(np.mean(valores)) #Calcula la media de los valores
print(np.median(valores))#Calvula la mediana de los valores
print(np.std(valores))#Calcula la desviacion estandar de los valores
print(np.var(valores))#Calcula la varianza de los valores
print(np.percentile(valores,75))#Calcula el percentil 75
print(np.percentile(valores,50))#Calcula el percentil 50
print(np.percentile(valores,25))#Calcula el percentil 25
print(np.percentile(valores,100))#Calcula el percentil 100


3.8181818181818183
3.0
2.405228464604173
5.785123966942148
5.0
3.0
2.0
9.0
